### ISSUE TITLE
Use vector graphics

### ISSUE THREAD

**Issue by alchemyst** [CR34M3/AHCampher_Thesis#1]
The current graphics are good enough for a first draft, but require some work.  I suggest using [PGF/TikZ](http://en.wikipedia.org/wiki/PGF/TikZ).  Have a look at [what's possible](http://www.texample.net/tikz/examples/).  It's probably already installed on your system - try "locate pgfmanual".  You can also try Inkscape, which has some macros for TeX support, or the humble Xfig.

**Comment by CR34M3** [comment]
Done [updating old issue]
